//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPV_Mark3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseSign
    {
        public int Id { get; set; }
        public int Case_Id { get; set; }
        public string CustSign { get; set; }
        public string VerifySign1 { get; set; }
        public string VerifySign2 { get; set; }
    
        public virtual CaseTable CaseTable { get; set; }
    }
}
