//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPV_Mark3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseImage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Case_Id { get; set; }
    
        public virtual CaseTable CaseTable { get; set; }
    }
}
