//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPV_Mark3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CaseTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaseTable()
        {
            this.CaseImages = new HashSet<CaseImage>();
        }
    
        public int Id { get; set; }


        [Required(ErrorMessage = "Application Name is required.")]
        public string Application_name { get; set; }
        public string Application_no { get; set; }
        public string Company_Name { get; set; }
        public string Trade_License_Number { get; set; }
        public string Company_Address { get; set; }
        public string Landmark { get; set; }
        public string Landline { get; set; }
        public string Contacted_Person { get; set; }
        public string Contacted_Person_Mobile_No { get; set; }
        public string Operating_Hours { get; set; }
        public string Emirate { get; set; }
        public string Product { get; set; }
        public string Visit_Type { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> Allocation_Date { get; set; }
        public string FE_Name { get; set; }
        public string Validated_Office_Landline { get; set; }
        public string Validated_Office_Landline_No { get; set; }
        public string Validated_Office_Landline_NotReason { get; set; }
        public string Source_of_Validated_Number { get; set; }
        public string Office_Location_Type { get; set; }
        public string Subject_company_signboard { get; set; }
        public string Available_OfficeDoor { get; set; }
        public string Different_CompanyNameBoard_Seen { get; set; }
        public string Different_CompanyNameBoard_Seen_Reason { get; set; }
        public string Type_Signboard_OnDoor { get; set; }
        public string Name_SocietyBoard { get; set; }
        public string SecurityGuard_Building { get; set; }
        public string ReceptionDesk { get; set; }
        public string BusinessActivity_Seen { get; set; }
        public string TradeLicense_Displayed { get; set; }
        public string Setup_of_Office { get; set; }
        public string Assets_Seen { get; set; }
        public string WebsiteAddress_Active { get; set; }
        public string Nature_of_Business { get; set; }
        public string Office_observation { get; set; }
        public Nullable<int> No_Employees_Seen { get; set; }
        public Nullable<int> No_Employees_ContactedPerson { get; set; }
        public string If_Sister_ConcernCompany { get; set; }
        public string Co_Owenrship_details { get; set; }
        public string External_Audit { get; set; }
        public string Annual_Revenue { get; set; }
        public string Applicants_Designation { get; set; }
        public string DoJ_Applicant { get; set; }
        public string Gross_Salary { get; set; }
        public string Profit { get; set; }
        public string Accommodation_Provided { get; set; }
        public string Applicant_Reports_to { get; set; }
        public string AUTHORIZED_SIGNATORY { get; set; }
        public string Details_Verified_With { get; set; }
        public string Designation { get; set; }
        public string Orginal_Seen { get; set; }
        public string Trade_License_captured { get; set; }
        public string Business_card_captured { get; set; }
        public string Documents_Captured { get; set; }
        public string VAT_RegNumber { get; set; }
        public string Makani_No { get; set; }
        public string Name_Neighbor1_feedback { get; set; }
        public string Name_Neighbor2_feedback { get; set; }
        public string Name_Security_feedback { get; set; }
        public string FE_Decision { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Feedback { get; set; }
        public string Images { get; set; }
        public string Verifier_Signature { get; set; }
        public string Customer_Signature { get; set; }
        public Nullable<System.DateTime> Final_Date { get; set; }
        public string Final_Status { get; set; }
        public string CustSign { get; set; }
        public string VerifySign1 { get; set; }
        public string VerifySign2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseImage> CaseImages { get; set; }
    }
}
