//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPV_Mark3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTable
    {
        public int Id { get; set; }
        public string Visit_Type { get; set; }
    }
}
